/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.exportSymbol('proto.pl.jcw.demo.chat.ChatMessage', null, global);
goog.exportSymbol('proto.pl.jcw.demo.chat.ReceiveMessagesRequests', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pl.jcw.demo.chat.ChatMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pl.jcw.demo.chat.ChatMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pl.jcw.demo.chat.ChatMessage.displayName = 'proto.pl.jcw.demo.chat.ChatMessage';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pl.jcw.demo.chat.ChatMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.pl.jcw.demo.chat.ChatMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pl.jcw.demo.chat.ChatMessage} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pl.jcw.demo.chat.ChatMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: msg.getMessage(),
    user: msg.getUser(),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pl.jcw.demo.chat.ChatMessage}
 */
proto.pl.jcw.demo.chat.ChatMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pl.jcw.demo.chat.ChatMessage;
  return proto.pl.jcw.demo.chat.ChatMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pl.jcw.demo.chat.ChatMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pl.jcw.demo.chat.ChatMessage}
 */
proto.pl.jcw.demo.chat.ChatMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUser(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pl.jcw.demo.chat.ChatMessage} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pl.jcw.demo.chat.ChatMessage.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pl.jcw.demo.chat.ChatMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pl.jcw.demo.chat.ChatMessage.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getUser();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pl.jcw.demo.chat.ChatMessage} The clone.
 */
proto.pl.jcw.demo.chat.ChatMessage.prototype.cloneMessage = function() {
  return /** @type {!proto.pl.jcw.demo.chat.ChatMessage} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.pl.jcw.demo.chat.ChatMessage.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.pl.jcw.demo.chat.ChatMessage.prototype.setMessage = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string user = 2;
 * @return {string}
 */
proto.pl.jcw.demo.chat.ChatMessage.prototype.getUser = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.pl.jcw.demo.chat.ChatMessage.prototype.setUser = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 3;
 * @return {proto.google.protobuf.Timestamp}
 */
proto.pl.jcw.demo.chat.ChatMessage.prototype.getTimestamp = function() {
  return /** @type{proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/** @param {proto.google.protobuf.Timestamp|undefined} value  */
proto.pl.jcw.demo.chat.ChatMessage.prototype.setTimestamp = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.pl.jcw.demo.chat.ChatMessage.prototype.clearTimestamp = function() {
  this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.pl.jcw.demo.chat.ChatMessage.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pl.jcw.demo.chat.ReceiveMessagesRequests = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pl.jcw.demo.chat.ReceiveMessagesRequests, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pl.jcw.demo.chat.ReceiveMessagesRequests.displayName = 'proto.pl.jcw.demo.chat.ReceiveMessagesRequests';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pl.jcw.demo.chat.ReceiveMessagesRequests.prototype.toObject = function(opt_includeInstance) {
  return proto.pl.jcw.demo.chat.ReceiveMessagesRequests.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pl.jcw.demo.chat.ReceiveMessagesRequests} msg The msg instance to transform.
 * @return {!Object}
 */
proto.pl.jcw.demo.chat.ReceiveMessagesRequests.toObject = function(includeInstance, msg) {
  var f, obj = {
    numberofmessages: msg.getNumberofmessages(),
    maxageseconds: msg.getMaxageseconds()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pl.jcw.demo.chat.ReceiveMessagesRequests}
 */
proto.pl.jcw.demo.chat.ReceiveMessagesRequests.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pl.jcw.demo.chat.ReceiveMessagesRequests;
  return proto.pl.jcw.demo.chat.ReceiveMessagesRequests.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pl.jcw.demo.chat.ReceiveMessagesRequests} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pl.jcw.demo.chat.ReceiveMessagesRequests}
 */
proto.pl.jcw.demo.chat.ReceiveMessagesRequests.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNumberofmessages(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxageseconds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.pl.jcw.demo.chat.ReceiveMessagesRequests} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.pl.jcw.demo.chat.ReceiveMessagesRequests.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pl.jcw.demo.chat.ReceiveMessagesRequests.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.pl.jcw.demo.chat.ReceiveMessagesRequests.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getNumberofmessages();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = this.getMaxageseconds();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.pl.jcw.demo.chat.ReceiveMessagesRequests} The clone.
 */
proto.pl.jcw.demo.chat.ReceiveMessagesRequests.prototype.cloneMessage = function() {
  return /** @type {!proto.pl.jcw.demo.chat.ReceiveMessagesRequests} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 numberOfMessages = 1;
 * @return {number}
 */
proto.pl.jcw.demo.chat.ReceiveMessagesRequests.prototype.getNumberofmessages = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.pl.jcw.demo.chat.ReceiveMessagesRequests.prototype.setNumberofmessages = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 maxAgeSeconds = 2;
 * @return {number}
 */
proto.pl.jcw.demo.chat.ReceiveMessagesRequests.prototype.getMaxageseconds = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.pl.jcw.demo.chat.ReceiveMessagesRequests.prototype.setMaxageseconds = function(value) {
  jspb.Message.setField(this, 2, value);
};


goog.object.extend(exports, proto.pl.jcw.demo.chat);
